---
driver:
  name: docker
driver_config:
  require_chef_omnibus: true
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list: apt

suites:
  - name: default