name 'mwser-ohmage'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures mwser-ohmage'
long_description 'Installs/Configures mwser-ohmage'
version '0.2.1'

depends 'mysql'
depends 'nginx'
depends 'mysql2_chef_gem'
depends 'database'
depends 'flyway'
